id: P674FDD2D
initial_creation_type: input
source_metadata:
  title: Guru Yoga Series
  language: zh
  description: 'A series of Guru Yoga (bla ma''i rnal ''byor) practices:'
  volume:
    967900771a484727b4802dd52f5d7582:
      title: 'Bestower of Supreme Blessings: Guru Yoga of the Great Incomparable Lord
        Atiśa'
      parent: Atiśa Dīpaṃkara
    db1683b34d5546adadcf734600d695da:
      title: Guru Yoga of the Guru Mahāmuni
      parent: Buddha Śākyamuni
    75aff60ca1764d9ea1e97322ddcf3a9d:
      title: 'The Merry Sea of Blessings: A Guru Yoga of the Lord of Sages, Peerless
        Teacher of All, Including the Devas'
      parent: Buddha Śākyamuni
    86cb4b16c0234154bbffa570c36431e0:
      title: A Profound and Concise Guru Yoga
      parent: Chatral Rinpoche
    8f50259bd434408b939b5bcb56048af0:
      title: The Guru Yoga of the Profound Path
      parent: Dorje Tötreng Tsal
    b0403747d7134da99160e9b921c640db:
      title: 'The Gathering of Blessings: A Guru Yoga'
      parent: Dzogchen
    fd28c8a7b9df40cab0b2dbf5b9e6a718:
      title: 'Guru Yoga: The Consummate Blessing'
      parent: Dzogchen
    f34066941ba2482fb96b4b58f1753d0a:
      title: Guru Yoga
      parent: Padmasambhava
    cfedb3fbb75349419b828e5431ff98cf:
      title: 'A Drop of Jewels: A Guru Yoga for Lord Gampopa'
      parent: Gampopa Sonam Rinchen
    a654d4910c5d47d68618f90978005c03:
      title: Guru Sādhana of Garab Dorje
      parent: Garab Dorje
    3a5976ae0cdb473ebd6015e8c3afeec1:
      title: 'A Shower of Wisdom: A Guru Yoga of Garab Dorje'
      parent: Garab Dorje
    cf3ac588d7dc4021b5c1c0ab85113d4d:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      parent: Gesar
    2e4572185d62470c95c3ddce73c6dfba:
      title: Guru Yoga of the Great Learned and Accomplished Ācārya Haribhadra
      parent: Haribhadra
    f8d1561010194988b27ab19e53446428:
      title: Guru Yoga – A Rang Rig Ma Chö
      parent: Jamyang Khyentse Chökyi Lodrö
    52e05f67672343958991cf9adda81068:
      title: Letter of Advice to Jamyang Gyaltsen
      parent: Jamyang Khyentse Chökyi Lodrö
    f6079bea2130431c9ff8cbc35524524c:
      title: 'Bestowing the Glory of Wisdom: A Gaṇacakra Feast for Nyingtik Saldrön'
      parent: Jamyang Khyentse Chökyi Lodrö
    f33baff5e0aa40db9d456945b2ee96d5:
      title: 'Drop of Wisdom Nectar: A Guru Yoga'
      parent: Jamyang Khyentse Chökyi Lodrö
    a16534a2623647598015e354abda4e4e:
      title: Guru Padma Yoga
      parent: Jamyang Khyentse Chökyi Lodrö
    084c7d785906415b84933a35f59d0e32:
      title: 'The Bright Lamp of Wisdom: A Guide to the Practice of Guru Yoga (Yeshe
        Saldrön)'
      parent: Jamyang Khyentse Chökyi Lodrö
    c66bd964baa049708eaa4f4e32ec5607:
      title: 'The Bright Lamp of the Heart Essence (Nyingtik Saldrön): A Guru Yoga'
      parent: Jamyang Khyentse Chökyi Lodrö
    b385c719fff846e7aa77e20eda390948:
      title: Guru Yoga of Rigdzin Jigme Lingpa
      parent: Jigme Lingpa
    0afbce998d6e4e518e384b35b5b008d8:
      title: 'The Swift Bestowal of Blessings: A Guru Yoga'
      parent: Khenchen Jigme Phuntsok
    6a69142141d742e4be50401b77c2cca2:
      title: Guru Yoga Focusing upon Noble Kurukullā
      parent: Kurukullā
    2d969763fa7942a298477d3377d05628:
      title: Guru Yoga of Jetsün Lochen, Queen of Yoginīs
      parent: Lochen Chönyi Zangmo
    40a1836c2b5c4e65a4c8ef2e835c2760:
      title: Guru Yoga of the Great Omniscient One, Longchenpa
      parent: Longchen Rabjam
    c20104299bbf40118b617150e1af04cb:
      title: 'Guru Yoga: The Complete Path of Sūtra And Tantra'
      parent: Mañjuśrī
    32fd543d1ac445cab764521ae8804bf8:
      title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the
        Three Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
      parent: Marpa, Milarepa & Gampopa
    ac1efbeebd274b1cbf86cc74d82c8668:
      title: A Combined Guru Yoga for Marpa, Mila, and Gampopa
      parent: Marpa, Milarepa & Gampopa
    743d076757764f07b2671baf241511fb:
      title: Guru Yoga of Lord Marpa Lotsāwa
      parent: Marpa Chökyi Lodrö
    23f89dc66bf1445f8b87924bff0f9835:
      title: 'A Drop of Sunshine: A Guru Yoga for Lord Marpa'
      parent: Marpa Chökyi Lodrö
    512ab9084cfa4a62964323a82a1ecf3c:
      title: Guru Yoga of Jetsün Shepa Dorje
      parent: Milarepa
    037e9310196842a78e1812a92ad26b34:
      title: 'A Drop of Moonlight: A Guru Yoga for Lord Mila'
      parent: Milarepa
    60db18158dfd4716b83f737f5eee398c:
      title: Supplication to Lord Mila Shepa Dorje
      parent: Milarepa
    f989a0a6d88042bdb8c252673f6c4798:
      title: Guru Yoga of Milarepa Shepa Dorje for Daily Practice
      parent: Milarepa
    74bf26069dfc49dcb795b8d65820c60c:
      title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
      parent: Mipham Rinpoche
    4ec2de90f3c04c9e8c762c523c28932d:
      title: 'The Radiant Treasure of Blessings: A Guru Yoga of the Great Vajradhara
        Ngawang Samten Lodrö'
      parent: Ngawang Samten Lodrö
    ce92e05533c04a728ff34f13ae6ed60c:
      title: A Concise Guru Yoga
      parent: Padmasambhava
    43fe24ae1ba34a31a50054258e6a77b7:
      title: 'The Quintessence of the Profound Path: A Concise Guide to the Stages
        of Visualization for the Guru Yoga of the Seven-Line Supplication, A Shower
        of Blessings'
      parent: Padmasambhava
    1c761f065f4b4a56aa31b4075a95c17c:
      title: 'The Swift Infusion of Blessings: A Prayer and Aspiration for the Stages
        of the Path Combined with Guru Yoga'
      parent: Padmasambhava
    e7f90892b14d4871828ce211afd776a0:
      title: 'The Wish-Fulfilling Jewel: The Outer Practice of Guru Yoga from the
        Heart-Essence of the Vast Expanse'
      parent: Padmasambhava
    7ac6e43b8f034274ab4e260c1318c76e:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven-Line
        Prayer'
      parent: Padmasambhava
    8ce8b3deaa80440a84dc5254ae2328ea:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line
        Prayer (Addendum)'
      parent: Padmasambhava
    0289ff8b408f408cbdd620dbec584514:
      title: Guru Yoga of the Great Tertön Pema Lingpa
      parent: Pema Lingpa
    386df1a7cff8497b980f997c6693a818:
      title: 'Shower of Blessings: A Guru Yoga of the Great Paṇḍita, Glorious Rongzom'
      parent: Rongzom Chökyi Zangpo
    b0332f77a1bb4408a64f02ebb8befed3:
      title: 'The Sun of Ambrosial Wisdom: A Guru Yoga of Dharmarāja Sakya Paṇḍita'
      parent: Sakya Paṇḍita
    f08d5a5835634cf9a5fa9682fba5e9d7:
      title: A Guru Yoga of Śavari
      parent: Śavari
    fe7c27b183da4d60824d74b5ccc787c2:
      title: 'The Profound Path of Guru Yoga: A Way to Freedom for the Fortunate'
      parent: Sera Khandro
    3a6a59e26eab4ea289be256310d26beb:
      title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
      parent: Smṛtijñānakīrti
    ad34e39f5f8243a6864a258392c2c88b:
      title: 'Self-Arising Wisdom: Songtsen Gampo Guru Sādhana'
      parent: Songtsen Gampo
    c37e6cb21a284bd1b2fc3cbfc3fe9255:
      title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the
        Three Deities of Long Life'
      parent: Three Deities of Long Life
    8d3d9c1169cc4f44bedd8bb8241f60da:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Three Mañjughoṣas
    188dddb375184359adb5b452426af9b4:
      title: 'The Quintessential Blessing: A Guru Yoga'
      parent: Trulshik Rinpoche
    efd0f280d811433e9d05c79cc12fc6cd:
      title: Short Guru Yoga of the Noble Lord, All-Knowing Tsongkhapa
      parent: Tsongkhapa Lobzang Drakpa
    108cb8b7459f4b21ba2df557134c8390:
      title: 'Cultivating the Pure Realm of Manifest Joy: A Guru Yoga of Vajrasattva'
      parent: Vajrasattva
created_at: '2022-03-01T03:55:16.216721'
last_modified_at: '2022-03-01T03:55:16.216723'
